spring.application.name=springai-langchain4j

# Ollama configuration (local Ollama must be running and accessible on the URL below)
spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b
spring.ai.ollama.embedding.options.model=nomic-embed-text

# Langchain4j (integration) configuration pointing to the local Ollama instance
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=llama3.2:1b


spring.ai.ollama.embedding.model=nomic-embed-text

spring.datasource.url=jdbc:postgresql://localhost:5433/rag
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=spring_ai_vector_store
spring.ai.vectorstore.pgvector.distance-type=cosine-distance
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.dimensions=768
