spring.application.name=springai-langchain4j

spring.ai.model.chat=openai
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL:gpt-4o-mini}

app.langchain4j.openai.api-key=${OPENAI_API_KEY:}
app.langchain4j.openai.model-name=${OPENAI_CHAT_MODEL:gpt-4o-mini}
